server:
  port: 8090

spring:
  application:
    name: gateway
  devtools:
    restart:
      enabled: true
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"  #请求来源
            allowedMethods: "*"  #请求的方式
            allowedHeaders: "*"  #允许携带请求头
            allowCredentials: true  #允许携带cookie
        # 解决options请求被拦截的问题
        add-to-simple-url-handler-mapping: true
      routes:
        - id: staff
          uri: http://127.0.0.1:8080
#          uri: lb://member # 负载均衡的
          predicates:
            - Path=/api/employee/**