server:
  port: 8080
spring:
  application:
    name: staff
  devtools:
    restart:
      enabled: true
      exclude: application.yml,static/**,public/**
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/staff?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: zzb200166
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

password:
  key: zzb2001661111111
